### ISSUE TITLE
How to save the subnet into a checkpoint？

### ISSUE THREAD

**Issue by steeellar** [mechanicalsea/lighthubert#7]
Hi, this work is awesome and helps me a lot.  But I don't how to save the subnet into a checkpoint , could you provide some ways to get the checkpoint of subnet? Thanks a lot.

**Comment by P1ping** [comment]
@Ref-rain Thanks for your attention! I noticed you have closed this issue. Did you solve this problem, or do you still need any help?

**Comment by steeellar** [comment]
> @Ref-rain Thanks for your attention! I noticed you have closed this issue. Did you solve this problem, or do you still need any help?

I have successfully exported it to onnx model， and the checkpoint for pytorch is not too necessary。Thanks for your apply.
